name: âœ… Manual Apply

on:
  workflow_dispatch:

jobs:
  apply_infra:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ssh_private_key: ${{ vars.SSH_PRIVATE_KEY_BASE64 }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra/terraform
        run: |
          terraform init \
            -backend-config="bucket=my-todo-app-tf-state" \
            -backend-config="key=todo-app/terraform.tfstate" \
            -backend-config="region=us-east-2" \
            -reconfigure

      - name: Terraform Apply
        working-directory: infra/terraform
        run: |
          set -eo pipefail
          terraform apply -auto-approve
