name: ‚ö†Ô∏è Drift Detection

on:
  push:
    branches: [main]
    #paths:
    # Trigger only if changes occur in the infrastructure directories
    #- "infra/terraform/**"
    #- "infra/ansible/**"

jobs:
  detect_drift:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ssh_private_key: ${{ vars.SSH_PRIVATE_KEY_BASE64 }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra/terraform
        run: |
          terraform init \
            -backend-config="bucket=my-todo-app-tf-state" \
            -backend-config="key=todo-app/terraform.tfstate" \
            -backend-config="region=us-east-2" \
            -reconfigure

      # Step 1: Run Terraform Plan to detect drift
      # This step will 'fail' (exit code 2) if drift is found. We use '|| true'
      # to prevent the overall workflow from stopping here, allowing us to
      # check the status later.
      - name: Run Terraform Plan (Drift Check)
        id: plan
        working-directory: infra/terraform
        run: |
          terraform refresh -input=false
          terraform plan -detailed-exitcode -out=tfplan.out || true

      - name: Set Exit Code Output
        id: exit_code_setter
        run: |
          # If the plan step failed due to exit code 2 (drift), set the output to 2.
          if [ "${{ steps.plan.outcome }}" == "failure" ]; then
            echo "exit_code=2" >> $GITHUB_OUTPUT
          else
            # If the plan succeeded (exit code 0), set output to 0.
            echo "exit_code=0" >> $GITHUB_OUTPUT
          fi

      - name: ‚úâÔ∏è Drift Alert
        # Check the custom output set in the previous step
        if: steps.exit_code_setter.outputs.exit_code == '2'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ vars.EMAIL_USERNAME }}
          password: ${{ vars.EMAIL_PASSWORD }}
          from: codedcoderrr@gmail.com
          subject: üö® INFRASTRUCTURE DRIFT DETECTED
          to: codedcoderrr@gmail.com
          body: |
            Terraform detected drift in the infrastructure.
            Manual review is required before applying changes.
            Commit: ${{ github.sha }}

      - name: Stop Run Due to Drift
        # Fail the overall job if drift is detected (exit code 2)
        if: steps.exit_code_setter.outputs.exit_code == '2'
        run: exit 2
